{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f816beed",
   "metadata": {},
   "source": [
    "# 0825_dongjin_024_xgb_native_thresholds (Updated to 006 Type-Conditioned Baseline)\n",
    "\n",
    "This notebook directly extracts the mathematical split thresholds learned by the XGBoost models. \n",
    "It uses the **0824_kimjaehak_006_type_conditioned_baseline.pkl** artifact, meaning there is a separate XGBoost model for each `inspection_type`.\n",
    "It parses the native XGBoost internal trees (`trees_to_dataframe()`) for each type's model to find exactly what boundary conditions trigger False Positives (False Calls)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0601d917",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "import joblib\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import shap\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "EXPERIMENT_ID = \"0825_dongjin_024_xgb_native_thresholds\"\n",
    "MODEL_PATH = Path(\"../models/0824_kimjaehak_006_type_conditioned_baseline.pkl\")\n",
    "DATA_PATH = Path(\"../data/raw/dataset.csv\")\n",
    "\n",
    "TARGET = \"class\"\n",
    "TIME_COLUMN = \"timestamp\"\n",
    "RECORD_ID = \"record_id\"\n",
    "DECISION_THRESHOLD = 0.5"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b092ad1d",
   "metadata": {},
   "source": [
    "## 1. Load Data and Reproduce Test Set Split"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2e8bc4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Load Data\n",
    "raw_df = pd.read_csv(DATA_PATH, low_memory=False)\n",
    "if raw_df.columns[0].startswith(\"Unnamed:\"):\n",
    "    raw_df = raw_df.rename(columns={raw_df.columns[0]: RECORD_ID})\n",
    "\n",
    "# 2. Deduplicate\n",
    "dedup_columns = [col for col in raw_df.columns if col not in {RECORD_ID, TIME_COLUMN}]\n",
    "clean_df = raw_df.loc[~raw_df.duplicated(subset=dedup_columns, keep=\"first\")].copy().reset_index(drop=True)\n",
    "\n",
    "# 3. Prepare inputs\n",
    "clean_df[TIME_COLUMN] = pd.to_datetime(clean_df[TIME_COLUMN], errors=\"raise\", utc=True)\n",
    "clean_df = clean_df.sort_values([TIME_COLUMN, RECORD_ID], kind=\"stable\").reset_index(drop=True)\n",
    "feature_columns = [col for col in clean_df.columns if col not in {RECORD_ID, TIME_COLUMN, TARGET}]\n",
    "\n",
    "X = clean_df[feature_columns].copy()\n",
    "y = clean_df[TARGET].astype(\"int8\").copy()\n",
    "timestamps = clean_df[TIME_COLUMN].copy()\n",
    "\n",
    "# 4. Load artifact to get validation_end_time\n",
    "artifact = joblib.load(MODEL_PATH)\n",
    "valid_end_time = artifact.get('validation_end_time')\n",
    "\n",
    "# If valid_end_time isn't set, fallback to 60/20/20 split\n",
    "if valid_end_time is None:\n",
    "    timestamp_group_sizes = timestamps.value_counts(sort=False).sort_index()\n",
    "    cumulative_rows = timestamp_group_sizes.cumsum().to_numpy()\n",
    "    valid_end_position = int(np.searchsorted(cumulative_rows, len(clean_df) * 0.80, side=\"left\"))\n",
    "    valid_end_time = timestamp_group_sizes.index[valid_end_position]\n",
    "else:\n",
    "    # Ensure timezone is applied if it's a string\n",
    "    valid_end_time = pd.to_datetime(valid_end_time, utc=True)\n",
    "\n",
    "test_mask = timestamps > valid_end_time\n",
    "X_test = X.loc[test_mask].copy()\n",
    "y_test = y.loc[test_mask].copy()\n",
    "\n",
    "print(f\"Test Set Size: {len(X_test)}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f11e558c",
   "metadata": {},
   "source": [
    "## 2. Analyze False Calls and Extract Thresholds (Per Inspection Type)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a86b6e88",
   "metadata": {},
   "outputs": [],
   "source": [
    "models_by_type = artifact['models_by_type']\n",
    "features_by_type = artifact['feature_columns_by_type']\n",
    "\n",
    "unique_types = sorted(X_test['inspection_type'].unique())\n",
    "\n",
    "for insp_type in unique_types:\n",
    "    print(\"=\" * 80)\n",
    "    print(f\"INSPECTION TYPE: {insp_type}\")\n",
    "    print(\"=\" * 80)\n",
    "    \n",
    "    if insp_type not in models_by_type:\n",
    "        print(f\"No model found for {insp_type}. Skipping.\")\n",
    "        continue\n",
    "        \n",
    "    model = models_by_type[insp_type]\n",
    "    type_features = features_by_type[insp_type]\n",
    "    \n",
    "    # 1. Filter test data for this type\n",
    "    X_test_type = X_test[X_test['inspection_type'] == insp_type].copy()\n",
    "    y_test_type = y_test[X_test['inspection_type'] == insp_type].copy()\n",
    "    \n",
    "    if len(X_test_type) == 0:\n",
    "        print(\"No test data for this type. Skipping.\")\n",
    "        continue\n",
    "        \n",
    "    # 2. Find False Calls\n",
    "    X_test_type_feats = X_test_type[type_features]\n",
    "    test_probabilities = model.predict_proba(X_test_type_feats)[:, 1]\n",
    "    test_predictions = (test_probabilities >= DECISION_THRESHOLD).astype(\"int8\")\n",
    "    \n",
    "    mask_fp = (y_test_type == 0) & (test_predictions == 1)\n",
    "    X_fp_type = X_test_type_feats[mask_fp]\n",
    "    \n",
    "    print(f\"Total False Calls for {insp_type}: {len(X_fp_type)}\\n\")\n",
    "    \n",
    "    if len(X_fp_type) == 0:\n",
    "        continue\n",
    "        \n",
    "    # 3. SHAP Analysis\n",
    "    explainer = shap.TreeExplainer(model)\n",
    "    shap_values_fp = explainer.shap_values(X_fp_type)\n",
    "        \n",
    "    mean_abs_shap = np.abs(shap_values_fp).mean(axis=0)\n",
    "    top_feature_indices = np.argsort(mean_abs_shap)[::-1][:10]\n",
    "    top_features = [type_features[idx] for idx in top_feature_indices]\n",
    "    \n",
    "    print(\"Top Features Driving False Calls (according to SHAP):\")\n",
    "    for i, feature in enumerate(top_features, 1):\n",
    "        print(f\"  {i}. {feature} (Mean |SHAP|: {mean_abs_shap[top_feature_indices[i-1]]:.4f})\")\n",
    "    \n",
    "    # 4. Extract Thresholds\n",
    "    booster = model.get_booster()\n",
    "    trees_df = booster.trees_to_dataframe()\n",
    "    \n",
    "    print(\"\\n-- Native Thresholds for Top Features --\")\n",
    "    for feature in top_features:\n",
    "        feature_nodes = trees_df[trees_df['Feature'] == feature]\n",
    "        if len(feature_nodes) == 0:\n",
    "            continue\n",
    "            \n",
    "        threshold_agg = feature_nodes.groupby('Split').agg(\n",
    "            Frequency=('Split', 'count'),\n",
    "            Total_Cover=('Cover', 'sum')\n",
    "        ).sort_values(by='Total_Cover', ascending=False)\n",
    "        \n",
    "        top_5 = threshold_agg.head(3)\n",
    "        thresholds_str = \", \".join([f\"< {th:.4f} (Cover: {row['Total_Cover']:.0f})\" for th, row in top_5.iterrows()])\n",
    "        print(f\"  * {feature}: {thresholds_str}\")\n",
    "        \n",
    "    print(\"\\n\")\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
